# ============================================================
# meta-packet-filter
# Yocto layer configuration
# ============================================================

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "packet-filter"

BBFILE_PATTERN_packet-filter = "^${LAYERDIR}/"

BBFILE_PRIORITY_packet-filter = "7"

LAYERDEPENDS_packet-filter = "core"

LAYERSERIES_COMPAT_packet-filter = "scarthgap"
